# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 746)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plot_osc_button = QtWidgets.QPushButton(self.centralwidget)
        self.plot_osc_button.setGeometry(QtCore.QRect(30, 50, 61, 23))
        self.plot_osc_button.setObjectName("plot_osc_button")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(29, 79, 761, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plot_osc = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plot_osc.setContentsMargins(0, 0, 0, 0)
        self.plot_osc.setObjectName("plot_osc")
        self.freq_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.freq_box.setGeometry(QtCore.QRect(90, 20, 62, 22))
        self.freq_box.setObjectName("freq_box")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(27, 21, 81, 21))
        self.textBrowser.setObjectName("textBrowser")
        self.set_freq_button = QtWidgets.QPushButton(self.centralwidget)
        self.set_freq_button.setGeometry(QtCore.QRect(150, 20, 75, 23))
        self.set_freq_button.setObjectName("set_freq_button")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 400, 761, 291))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.plot_auto = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.plot_auto.setContentsMargins(0, 0, 0, 0)
        self.plot_auto.setObjectName("plot_auto")
        self.set_time_button = QtWidgets.QPushButton(self.centralwidget)
        self.set_time_button.setGeometry(QtCore.QRect(620, 20, 71, 23))
        self.set_time_button.setObjectName("set_time_button")
        self.time_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.time_box.setGeometry(QtCore.QRect(557, 20, 61, 22))
        self.time_box.setObjectName("time_box")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(470, 20, 111, 21))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.set_voltage_button = QtWidgets.QPushButton(self.centralwidget)
        self.set_voltage_button.setGeometry(QtCore.QRect(620, 50, 71, 23))
        self.set_voltage_button.setObjectName("set_voltage_button")
        self.voltage_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltage_box.setGeometry(QtCore.QRect(557, 50, 62, 22))
        self.voltage_box.setObjectName("voltage_box")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(470, 50, 111, 21))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(710, 20, 71, 23))
        self.start_button.setObjectName("start_button")
        self.set_freq_res_button = QtWidgets.QPushButton(self.centralwidget)
        self.set_freq_res_button.setGeometry(QtCore.QRect(230, 20, 75, 23))
        self.set_freq_res_button.setObjectName("set_freq_res_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(710, 50, 71, 23))
        self.stop_button.setObjectName("stop_button")
        self.auto_acquire_button = QtWidgets.QPushButton(self.centralwidget)
        self.auto_acquire_button.setGeometry(QtCore.QRect(30, 370, 111, 23))
        self.auto_acquire_button.setObjectName("auto_acquire_button")
        self.set_freq_opt_button = QtWidgets.QPushButton(self.centralwidget)
        self.set_freq_opt_button.setGeometry(QtCore.QRect(310, 20, 75, 23))
        self.set_freq_opt_button.setObjectName("set_freq_opt_button")
        self.save_osc_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_osc_button.setGeometry(QtCore.QRect(310, 50, 75, 23))
        self.save_osc_button.setObjectName("save_osc_button")
        self.save_acquisition_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_acquisition_button.setGeometry(QtCore.QRect(360, 370, 75, 23))
        self.save_acquisition_button.setObjectName("save_acquisition_button")
        self.file_name_auto_input = QtWidgets.QLineEdit(self.centralwidget)
        self.file_name_auto_input.setGeometry(QtCore.QRect(210, 371, 141, 20))
        self.file_name_auto_input.setObjectName("file_name_auto_input")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(150, 370, 111, 21))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.file_name_osc_inout = QtWidgets.QLineEdit(self.centralwidget)
        self.file_name_osc_inout.setGeometry(QtCore.QRect(160, 51, 141, 20))
        self.file_name_osc_inout.setObjectName("file_name_osc_inout")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(100, 50, 111, 21))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_7.raise_()
        self.textBrowser_4.raise_()
        self.textBrowser_3.raise_()
        self.textBrowser_2.raise_()
        self.plot_osc_button.raise_()
        self.verticalLayoutWidget.raise_()
        self.textBrowser.raise_()
        self.freq_box.raise_()
        self.set_freq_button.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.set_time_button.raise_()
        self.time_box.raise_()
        self.set_voltage_button.raise_()
        self.voltage_box.raise_()
        self.start_button.raise_()
        self.set_freq_res_button.raise_()
        self.stop_button.raise_()
        self.auto_acquire_button.raise_()
        self.set_freq_opt_button.raise_()
        self.save_osc_button.raise_()
        self.save_acquisition_button.raise_()
        self.file_name_auto_input.raise_()
        self.file_name_osc_inout.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plot_osc_button.setText(_translate("MainWindow", "Plot"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Beat-note:</p></body></html>"))
        self.set_freq_button.setText(_translate("MainWindow", "Set freq."))
        self.set_time_button.setText(_translate("MainWindow", "Set Time"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Time Range:</p></body></html>"))
        self.set_voltage_button.setText(_translate("MainWindow", "Set Voltage"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Voltage Range:</p></body></html>"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.set_freq_res_button.setText(_translate("MainWindow", "Resonance"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.auto_acquire_button.setText(_translate("MainWindow", "Automatic Acquisition"))
        self.set_freq_opt_button.setText(_translate("MainWindow", "Optimal"))
        self.save_osc_button.setText(_translate("MainWindow", "Save"))
        self.save_acquisition_button.setText(_translate("MainWindow", "Save"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">File Name:</p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">File Name:</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
